version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /apps/api
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /packages/config
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /packages/engine
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /packages/shared
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /packages/wcl-types
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /tooling/typescript-config
    schedule:
      interval: weekly
